src/ShopifyApp/Traits/AuthControllerTrait.php, src/ShopifyApp/resources/config/shopify-app.php, tests/Controllers/AuthControllerTest.php, tests/Stubs/AfterAuthenticateJobStub.php
=> Feature after authenticate job

src/ShopifyApp/Middleware/AuthShop.php, src/ShopifyApp/resources/config/shopify-app.php, src/ShopifyApp/resources/views/layouts/default.blade.php, tests/Controllers/HomeControllerTest.php, tests/Middleware/AuthShopMiddlewareTest.php
The ability to disable ESDK and use legacy mode.
=> Legacy mode

src/ShopifyApp/Traits/AuthControllerTrait.php, tests/Controllers/AuthControllerTest.php
Fixes part of https://github.com/ohmybrew/laravel-shopify/issues/68
=> Fix bug with non-secure redirect URL.

.travis.yml, README.md, composer.json, src/ShopifyApp/Console/WebhookJobMakeCommand.php, src/ShopifyApp/Models/Shop.php, src/ShopifyApp/Observers/ShopObserver.php, src/ShopifyApp/Scopes/NamespaceScope.php, src/ShopifyApp/ShopifyAppProvider.php, src/ShopifyApp/resources/config/shopify-app.php, src/ShopifyApp/resources/database/migrations/2018_08_30_114021_add_namespace_to_shops_table.php, tests/Console/WebhookJobMakeCommandTest.php, tests/Observers/ShopObserverTest.php, tests/Scopes/NamespaceScopeTest.php
Adds ability to namespace apps.
Changes:
1. Added `namespace` column to shop table
2. Global scope to Shop model which appends `where namespace = ?` to all queries
3. An observer to automatically add namespace to a new shop on create
4. New config entry to define namespace either via config PHP file for env
Tests pass, physical tests seem fine. Reviewing.
=> Namespacing

src/ShopifyApp/Jobs/AppUninstalledJob.php
=> Get shop model from config

src/ShopifyApp/ShopifyAppProvider.php
instead of exporting them to the app's migration folder
=> load migrations from the package

src/ShopifyApp/Middleware/AuthShop.php
in Laravel 5.7 I had trouble to get store domain from session, so I  made sure that we have store in middleware
=> make sure that we always have store address

src/ShopifyApp/resources/config/shopify-app.php
myshopify domain can be managed through environment variables
=> Configurable myshopify domain

src/ShopifyApp/ShopifyAppProvider.php
in order to override the views of the package with custom html/css
=> add publish of shopify-views

src/ShopifyApp/Middleware/AuthShop.php
move ->setShop(...) outside the `elseif` with `$session->isValid()` check
=> simplify auth and bugfix

src/ShopifyApp/Middleware/AuthShop.php
Moves the logic to its own self-contained method. Flatten the method to make it easier to read.
=> Refactors the functionality to get the flow type.

src/ShopifyApp/Middleware/AuthShop.php
According to https://github.com/ohmybrew/laravel-shopify/pull/298 and the PR that i closed before for the issue https://github.com/ohmybrew/laravel-shopify/issues/295
=> Fix for session clashes also for Single-Page-Apps

.travis.yml
=> Add PHP 7.3 to travis

composer.json
Laravel 7 in composer.json
Solves : #404
=> Adds Laravel 7 support

.github/workflows/ci.yml
Test on PHP 7.4 as well as 7.3
=> Add PHP 7.4 to GitHub Action

src/ShopifyApp/Actions/AuthorizeShop.php
Since shopModel change to userModel and the email field is unique also userModel use SoftDelete, we should handle when the shop reinstalling the app.
=> Fix reinstall app

src/ShopifyApp/resources/jobs/AppUninstalledJob.php
Updated AppUninstalledJob inside the job that will be published via the command. Since now this job is moved to Messaging directory.
=> Updated namespace of AppUninstalledJob

src/ShopifyApp/Console/stubs/webhook-job.stub
=> ShopDomain object instead of string in webhook-job stub

src/ShopifyApp/resources/database/migrations/2020_07_03_211514_add_interval_column_to_charges_table.php
Fixes table name typo for down method in migration AddIntervalColumnToChargesTable
=> Fixes #544

src/ShopifyApp/Actions/CreateScripts.php, src/ShopifyApp/Contracts/ApiHelper.php, src/ShopifyApp/Services/ApiHelper.php, tests/Actions/CreateScriptsTest.php, tests/Actions/DispatchScriptsTest.php, tests/Services/ApiHelperTest.php
- Adds function to delete script tags
- Automatically delete unused script tags from shop
=> Adds ability to delete unused script tags

.github/workflows/ci.yml, composer.json
Check `composer.json` normalization in CI workflow: see failing test here https://github.com/osiset/laravel-shopify/pull/561/checks?check_run_id=1040588204#step:6:5
---
Add support section and extra config to composer.json file and normalize the `composer.json` file (by running `composer normalize`)
=> Normalize composer.json

src/ShopifyApp/Actions/ActivateUsageCharge.php, src/ShopifyApp/Actions/AfterAuthorize.php, src/ShopifyApp/Actions/AuthenticateShop.php, src/ShopifyApp/Actions/AuthorizeShop.php, src/ShopifyApp/Actions/CancelCharge.php, src/ShopifyApp/Actions/CancelCurrentPlan.php, src/ShopifyApp/Actions/CreateScripts.php, src/ShopifyApp/Actions/CreateWebhooks.php, src/ShopifyApp/Actions/DeleteWebhooks.php, src/ShopifyApp/Actions/DispatchScripts.php, src/ShopifyApp/Actions/DispatchWebhooks.php, src/ShopifyApp/Http/Middleware/AuthProxy.php, src/ShopifyApp/Http/Middleware/AuthShopify.php, src/ShopifyApp/Http/Middleware/Billable.php, src/ShopifyApp/Messaging/Events/AppLoggedIn.php, src/ShopifyApp/Messaging/Jobs/AppUninstalledJob.php, src/ShopifyApp/Messaging/Jobs/ScripttagInstaller.php, src/ShopifyApp/Messaging/Jobs/WebhookInstaller.php, src/ShopifyApp/Objects/Transfers/UsageCharge.php, src/ShopifyApp/Objects/Values/ShopDomain.php, src/ShopifyApp/Services/CookieHelper.php, src/ShopifyApp/Services/ShopSession.php, src/ShopifyApp/Storage/Observers/Shop.php, src/ShopifyApp/Storage/Queries/Shop.php
Fix all constructor return docblocks signatures, as they should be `@return void`
=> Fix all constructor return docblocks signatures

src/ShopifyApp/Services/ChargeHelper.php, src/ShopifyApp/helpers.php
Always prefer stricter comparisons
=> Always prefer stricter comparisons

.gitattributes, .styleci.yml
Add a `.styleci.yml` file.
@osiset, this repository needs to be activated at https://styleci.io (free for public repositories).
=> Add a .styleci.yml file

.github/workflows/ci.yml, .gitignore, composer.json
No need to keep `bin` directory.
=> No need to keep bin directory.

.github/workflows/ci.yml, composer.json
=> Do not hardcode dev package.

tests/Actions/AuthorizeShopTest.php, tests/Actions/CreateScriptsTest.php, tests/Actions/CreateWebhooksTest.php, tests/Actions/DeleteWebhooksTest.php, tests/Console/WebhookJobMakeCommandTest.php, tests/HelpersTest.php, tests/Http/Middleware/AuthProxyTest.php, tests/Http/Middleware/AuthWebhookTest.php, tests/Http/Middleware/BillableTest.php, tests/Services/ApiHelperTest.php, tests/Services/ChargeHelperTest.php, tests/Services/CookieHelperTest.php, tests/Services/ShopSessionTest.php, tests/Storage/Commands/ShopTest.php, tests/Storage/Models/ChargeTest.php, tests/Storage/Models/PlanTest.php, tests/Storage/Queries/PlanTest.php, tests/Storage/Queries/ShopTest.php, tests/Traits/HomeControllerTest.php, tests/Traits/ShopModelTest.php
Always use stricter and proper assertions.
=> Always use proper assertions.

src/ShopifyApp/resources/database/migrations/2020_01_29_230905_create_shops_table.php
=> Added check for if soft delete

src/ShopifyApp/resources/views/itp/ask.blade.php
=> Fix for Chrome and requestStorageAccess

src/ShopifyApp/Http/Middleware/ITP.php, src/ShopifyApp/Traits/ItpController.php
There were a few places that weren't using named routes from the config, so I tracked down all that I could find and fixed them.
=> Use named routes from config

.github/workflows/ci.yml, composer.json
This PR adds the missing `json` extension.
=> Add missing json extension.

tests/Actions/ActivateUsageChargeTest.php, tests/Actions/CancelChargeTest.php, tests/HelpersTest.php, tests/Http/Middleware/AuthShopifyTest.php, tests/Http/Middleware/AuthTokenTest.php, tests/Services/ApiHelperTest.php
This PR tests the message and code of ALL expected exceptions.
=> Also test the message and code of ALL expected exceptions.

tests/Actions/DeleteWebhooksTest.php
This PR ensures that all classes names are PSR4 compliant.
=> Ensure that all classes names are PSR4 compliant.

tests/Traits/ShopAccessibleTest.php, tests/Traits/Stubs/TestShopAccessible.php
This PR ensures that a file only contain one class.
The stub can be extracted in its own file.
=> Ensure that a file only contain one class.

src/ShopifyApp/Http/Middleware/AuthToken.php, src/ShopifyApp/Services/CookieHelper.php, src/ShopifyApp/Traits/ShopModel.php, src/ShopifyApp/helpers.php
Remove all useless braces in the code.
=> Remove useless braces.

tests/Messaging/Jobs/AppUninstalledTest.php, tests/Services/CookieHelperTest.php, tests/Stubs/OrdersCreateJob.php, tests/TestCase.php, tests/Traits/ShopModelTest.php
Add return types for functions in `/tests`
=> Add return types for functions in tests

src/ShopifyApp/Http/Middleware/AuthProxy.php, src/ShopifyApp/Http/Middleware/AuthToken.php, src/ShopifyApp/Services/CookieHelper.php
Use null coalescence when possible
=> Use null coalescence

src/ShopifyApp/Actions/AuthorizeShop.php, tests/Actions/AfterAuthorizeTest.php, tests/HelpersTest.php, tests/Stubs/Kernel.php, tests/TestCase.php, tests/Traits/WebhookControllerTest.php
=> Avoid using FQCN

.github/workflows/ci.yml
Replace abandoned package `cedx/coveralls` by `php-coveralls/php-coveralls`
=> Replace abandoned package cedx/coveralls

.github/workflows/ci.yml
This PR enables faster CI builds and tests by caching composer dependencies.
=> Cache composer dependencies

tests/Actions/AfterAuthorizeTest.php, tests/HelpersTest.php, tests/Http/Requests/StoreUsageChargeTest.php, tests/Stubs/AfterAuthorizeJob.php, tests/Traits/WebhookControllerTest.php
This PR enforces PSR4 namespaces for tests
=> Enforce PSR4 namespaces for tests

src/ShopifyApp/Actions/ActivatePlan.php
This PR optimises the filling of the transfer object depending on the recurrence.
=> No need to check 3 times for the same condition.

src/ShopifyApp/Actions/AfterAuthorize.php, src/ShopifyApp/Actions/DispatchWebhooks.php, src/ShopifyApp/Actions/GetPlanUrl.php
This PR simplifies some conditions.
=> Simplify some conditions.

src/ShopifyApp/Http/Middleware/AuthProxy.php, src/ShopifyApp/Http/Middleware/AuthToken.php, src/ShopifyApp/Http/Middleware/AuthWebhook.php
This PR enforces time safe string comparison.
=> Enforce time safe string comparison.

src/ShopifyApp/Console/WebhookJobMakeCommand.php
This PR removes a useless check.
Also we can return the result of the parent command.
=> Remove useless check.

.github/workflows/ci.yml
Set specific CI flags for validation, normalization and coverage.
This extra checks will only run for once php8 with laravel8.22
=> Set specific CI flags.

tests/Objects/Transfers/ChargeTest.php
This PR improves code-coverage.
=> Improve code-coverage.

.gitattributes, .github/workflows/ci.yml, composer.json, phpstan.neon, src/ShopifyApp/ShopifyAppProvider.php, src/ShopifyApp/Storage/Queries/Charge.php, tests/Stubs/Api.php
Introduce some Static analysis with `phpstan`.
For now the level is only 1, the goal is to do step by step to 8
=> Introduce some Static analysis.

.gitignore
Simplify and cleanup `.gitignore` file
=> Simplify and cleanup .gitignore file

tests/Actions/AuthorizeShopTest.php, tests/Http/Middleware/AuthTokenTest.php, tests/Services/ChargeHelperTest.php, tests/Storage/Commands/ChargeTest.php, tests/TestCase.php, tests/Traits/ApiControllerTest.php
Use `CarbonImmutable::setTestNow` feature for tests
=> Use CarbonImmutable testNow feature for tests

composer.json
=> Remove useless dependencies.

src/ShopifyApp/resources/routes/api.php, src/ShopifyApp/resources/routes/shopify.php
Use `::class` notations for routes controllers
=> Use ::class notations for routes controllers

tests/Messaging/Jobs/AppUninstalledTest.php, tests/Traits/ApiControllerTest.php
=> Remove useless methods

src/ShopifyApp/Http/Middleware/AuthShopify.php, src/ShopifyApp/Services/ApiHelper.php, tests/Actions/AuthenticateShopTest.php, tests/Http/Middleware/AuthTokenTest.php, tests/Http/Middleware/AuthWebhookTest.php, tests/Storage/Queries/ShopTest.php, tests/Traits/ApiControllerTest.php
This PR removes useless variables.
=> Remove useless variables.

tests/Actions/AuthorizeShopTest.php, tests/Http/Middleware/AuthTokenTest.php, tests/Services/ApiHelperTest.php, tests/Traits/ApiControllerTest.php, tests/Traits/AuthControllerTest.php
Use `Util::getShopifyConfig()` instead of `env()`.
=> Use Util::getShopifyConfig instead of env.

src/ShopifyApp/ShopifyAppProvider.php, tests/Actions/ActivateUsageChargeTest.php, tests/Actions/CancelChargeTest.php, tests/Objects/Transfers/ChargeTest.php
Enforce [PSR12](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/3.0/doc/ruleSets/PSR12.rst) standards.
=> Enforce PSR12 standards.

tests/Macros/TokenRedirectTest.php, tests/Macros/TokenRouteTest.php, tests/Objects/Transfers/ChargeTest.php, tests/Objects/Values/SessionTokenTest.php, tests/UtilTest.php
=> Use stricter assertions.

tests/Actions/AfterAuthorizeTest.php, tests/Objects/Values/SessionTokenTest.php, tests/Traits/ApiControllerTest.php
Remove unexpected arguments, as some methods expect a specific number of arguments.
=> Remove unexpected arguments.

src/ShopifyApp/Actions/ActivateUsageCharge.php, src/ShopifyApp/Actions/CancelCurrentPlan.php, src/ShopifyApp/Contracts/ApiHelper.php, src/ShopifyApp/Contracts/Commands/Charge.php, src/ShopifyApp/Contracts/Commands/Shop.php, src/ShopifyApp/Contracts/Queries/Shop.php, src/ShopifyApp/Services/ApiHelper.php, src/ShopifyApp/Util.php
=> Fix many docblocks.

.github/workflows/ci.yml
Improve cache with taking in consideration `laravel/legacy-factories` and `illuminate/contracts`.
=> Also cache laravel/legacy-factories and illuminate/contracts.

src/ShopifyApp/ShopifyAppProvider.php
Reformat and clean-up service provider.
- remove implicit comments
- make the bindings in the container much easier to read (IMO)
=> Reformat and clean-up service provider

src/ShopifyApp/Http/Middleware/AuthProxy.php, src/ShopifyApp/Http/Middleware/Billable.php, src/ShopifyApp/Services/CookieHelper.php, src/ShopifyApp/resources/views/partials/flash_messages.blade.php
This PR optimizes many conditions.
=> Optimize conditions

.php-cs-fixer.dist.php, src/ShopifyAppProvider.php
This PR excludes a file which should not be checked for Style violation
And fix another file for code violations.
=> Exclude file

.github/FUNDING.yml, FUNDING.md, composer.json
Add Github as a funding possibility.
=> Add Github as a funding possibility.

src/Http/Middleware/VerifyShopify.php
fixed ignoring installation the first time, will cause an installation failure next time for #932
=> Fixed installation issue

src/Traits/AuthController.php
This will fix Safari related issue: https://github.com/osiset/laravel-shopify/issues/950
=> Add shop to parameter if we already have it

src/Traits/AuthController.php, tests/Traits/AuthControllerTest.php
=> Fix getDomain() error and throw catchable exception

.github/workflows/ci.yml, src/Traits/AuthController.php, src/resources/views/auth/fullpage_redirect.blade.php, tests/Traits/AuthControllerTest.php
@Kyon147 had a moment. didn't think this would end up being especially large
=> Olavosantos 1094 issue branch w/ updated tests

README.md
Remove a 3-year old "coming soon"
Remove the roadmap link as the wiki page is empty
=> Update old readme info
