README.md
composer.json
composer.lock
src/ShopifyApp/Console/WebhookJobMakeCommand.php
tests/Models/ShopModelTest.php

For issue #3. Support laravel 5.5.
Not many changes needed, mainly for our artisan command to use handle instead of fire. 5.4 is still working with the package.

Changes to support 5.5

---

src/ShopifyApp/Libraries/BillingPlan.php
src/ShopifyApp/Traits/BillingControllerTrait.php
src/ShopifyApp/resources/config/shopify-app.php
tests/Controllers/BillingControllerTest.php
tests/Libraries/BillingPlanTest.php

To support issue #21 this adds ability to pass `capped_amount` and `terms` to the billing screen.

Usage support built in to the plan init

---

.coveralls.yml
.gitattributes
.gitignore
.travis.yml
README.md
composer.json

In this request:
- Remove `.coveralls.yml` file (Coveralls will be corrected with TravisCI automatic)
- Add `.gitattributes` file for line ending (LF) and  exclude `tests` folder when `composer require`
- Update `.gitignore` file for ignoring some IDE and OS files
- Update `.travis.yml` for testing with Laravel 5.5 & 5.6, PHP 7+
- Update `composer.json` for fix some errors with Laravel 5.6

[Feature] Update TravisCI for testing Laravel 5.6

---

src/ShopifyApp/Jobs/ScripttagInstaller.php
src/ShopifyApp/Jobs/WebhookInstaller.php

While using ShopModelTrait, base Shop model or its child class is not passed in constructor of two jobs, `WebhookInstaller` and `ScriptTagInstaller`, so we can remove the type hinting from constructor to solve this issue.

Adjustment to job classes for loose checking in constructor

---

src/ShopifyApp/Middleware/AuthShop.php

An additional fix in regards to https://github.com/ohmybrew/laravel-shopify/issues/164#issuecomment-457462347
> `return response()->json(Model::all());`
> 
> Yields a response that is text/html; charset=UTF-8 but looks like
> 
> ```
> HTTP/1.1 200 OK
> Cache-Control: no-cache, private
> Content-Type:  application/json
> Date:          Fri, 25 Jan 2019 05:39:47 GMT
> 
> []
> ```

Fix/Check if is already a JsonResponse

---

src/ShopifyApp/Console/stubs/webhook-job.stub

Fixing incorrect variable name in DocBlock . Used the same naming as in `src/ShopifyApp/Jobs/AppUninstalledJob.php`

Fix incorrect DocBlock

---

src/ShopifyApp/Middleware/AuthShop.php
src/ShopifyApp/Services/ShopSession.php

Hi @ohmybrew , when i was debugging to find the solutions for https://github.com/ohmybrew/laravel-shopify/issues/289 i found another issue. 
In the screenshot you can see that the shopDomainSession is not equal the shopDomainParam. For the first time you call the App via ShopifyAdmin->Apps->YourApp thats no problem but when you are inside the App and click somewhere you will see the content of the Shop that comes from shopDomainSession.
You can easily test it with 2 stores using the same App.
If you have questions, feel free to ask them :)

Bugfix - when shopDomainSession is not equal $shopDomainParam from request

---

src/ShopifyApp/Middleware/AuthShop.php
tests/Middleware/AuthShopMiddlewareTest.php

Sessions were clashing when a user was managing the same app for multiple stores in the same browser.
Both stores have the same session due to them both using the app domain in the same browser.
This was leading to store A overwriting store B or vice-versa.
A solution for normal req/resp apps (i.e. not SPAs) is to check the referer header to see exactly which store we're dealing with.
Because the referer header is spoofable we make sure that there is a valid HMAC signature present in the referer.
If there is a shop domain with a valid HMAC signature in the referer header then we overwrite the shopDomain variable to make sure the correct store is loaded.
Resolves https://github.com/ohmybrew/laravel-shopify/issues/295

Fix for session clashes

---

README.md
src/ShopifyApp/Middleware/AuthShop.php
tests/Middleware/AuthShopMiddlewareTest.php

It was possible for an attacker to successfully load a different stores information into memory via insecure direct object references.
You could simply change the domain in the get variables to another valid store and the application would successfully load their shop.
To fix this we add verification at the point of entry, and before we load the target shops sensitive model data into memory.
- [Line 52](https://github.com/ohmybrew/laravel-shopify/blob/master/src/ShopifyApp/Middleware/AuthShop.php#L52) loads the shop specified by the user
- [Line 59](https://github.com/ohmybrew/laravel-shopify/blob/master/src/ShopifyApp/Middleware/AuthShop.php#L59) then loads this value, without any validation, into the session
From that point on the arbitrary target shop is loaded. It's important that …

Security Fix for A4 IDOR Vulnerability

---

.travis.yml
composer.json
tests/Middleware/AuthProxyMiddlewareTest.php
tests/Middleware/AuthShopMiddlewareTest.php

Adding support for Laravel 6.
Note that the `Input` facade has been [deprecated](https://laravel.com/docs/6.0/upgrade#the-input-facade) in favour of `Request`. 2 tests have been updated accordingly. 
Unit tests contain 12 warnings as there are some annotations that are going to be depreciated soon.
This is my first PR here! Any feedback is appreciated!

Laravel 6 compatibility

---

src/ShopifyApp/resources/config/shopify-app.php
src/ShopifyApp/resources/views/layouts/default.blade.php

This PR add a setting for specifying the [Shopify App Bridge](https://help.shopify.com/en/api/embedded-apps/app-bridge/getting-started#embed-your-app-in-the-shopify-admin) version that is used in the CDN.
We are right now using the CDN endpoint which uses the latest version of Shopify App Bridge. This may contain breaking changes at some point (like when they go from version `1` to `2`) which would affect the applications using the latest CDN.
See the recommendation from Shopify [here](https://help.shopify.com/en/api/embedded-apps/app-bridge/getting-started#embed-your-app-in-the-shopify-admin):
> It’s not a good idea to automatically consume the latest version of a library in a production app, because a new version might introduce breaking changes.
**NO**. This implements a new …

Add App Bridge Version to configuration

---

src/ShopifyApp/resources/config/shopify-app.php

Spotted a typo in the new `appbridge_version` config incorrectly casting to a boolean, resulting in the URL to app bridge always returning a 1 or a 0 rather than the actual config value.

Bug fix: `appbridge_version` incorrectly casting to boolean

---

src/ShopifyApp/Exceptions/BaseException.php

I believe @ohmybrew meant to write `app.debug` since `shopify-app.debug` doesn't actually exist. (Reference: https://github.com/ohmybrew/laravel-shopify/issues/327#issuecomment-536872852)

Typo: changed `shopify-app.debug` key to `app.debug`

---

src/ShopifyApp/Services/UsageCharge.php

Hi @ohmybrew , we extended the charges table for usageCharges and saw that the save method just return the result of the eloquent save operation. To get the charge model after saving we changed this. Please take a look and maybe discuss :)
Have a nive day! Stefan

UsageCharge Service - return Charge Model instead of boolean

---

src/ShopifyApp/Traits/AuthControllerTrait.php

Shop should be added to session only when the code from shopify is valid. 
Right now you can login to any app using offline grant by going to app_url/authenticate?shop=shopdomain, after that you go to the app and you are logged in.

Fix broken auth

---

.travis.yml
src/ShopifyApp/Services/ShopSession.php
tests/Services/ShopSessionTest.php

A bug was discovered from PR #382 in `ShopSession.php`'s new `getBrowserDetails()` and `getPlatformDetails()` method that causes the app to not return SameSite=none on some platforms. This is likely caused by the fact that some platform's version numbers do not have a minor number. 
The proposed fix is to rely on `Jenssegers\Agent`'s built-in functions that can generate a float version number from any user-agent.
Reference: https://github.com/ohmybrew/laravel-shopify/pull/382#issuecomment-581620833_
Other fixes include:
- A mistake in the unit-test, where a compatible UCBrowser user-agent wound up in the incompatible list (confusion probably caused because both "Chrome" and "UCBrowser" is mentioned in the user-agent).
- Flipping the logic from a whitelist to a blacklist, since …

Bug fix for incorrect SameSite=none behaviour on some platforms.

---

src/ShopifyApp/resources/database/migrations/2020_01_29_231006_create_charges_table.php

On August 18, 2018, Laravel merged a change into all new user migrations. Laravel no longer sets the `id` column on the `users` table to `integer`, but instead uses `bigInteger`. The charges migration contained a `user_id` column that was not compatible with newer Laravel apps for this reason.
While you can publish your own migrations and make adjustments, if you're wanting to support newer Laravel versions going forward it should be changed to `bigInteger`. This pull request makes that change.

Made user_id on charges migration reflect Laravel's change of user id column

---

src/ShopifyApp/resources/database/migrations/2020_01_29_230905_create_shops_table.php

This PR fixes 1 issue and cleans up some unused data.
**Issue**
When working on the database in dev it's common to run `php artisan migrate:refresh --seed`. When attempting to refresh a database that already has tables, columns and data it throws the following error:
Illuminate\Database\QueryException 
SQLSTATE[HY000]: General error: 1828 Cannot drop column 'plan_id': needed in a foreign key constraint 'users_plan_id_foreign' (SQL: alter table `users` drop `shopify_grandfathered`, drop `shopify_namespace`, drop `shopify_freemium`, drop `plan_id`)
at vendor/laravel/framework/src/Illuminate/Database/Connection.php:669
665|         // If an exception occurs when attempting to run a query, we'll format the error
666|         // message to include the bindings with SQL, which will make this …

Added dropForeign and removed call to drop unused columns

---

src/ShopifyApp/Objects/Transfers/PlanDetails.php
src/ShopifyApp/Services/ChargeHelper.php

Changed "cappedTerms" to "terms" for api request when selecting a plan with a non-negative value of 'capped_amount'.

Changed "cappedTerms" to "terms" 

---

src/ShopifyApp/Storage/Queries/Charge.php

Charge model using SoftDelete. When shop reinstalling app and recharge billing with trial plan, we should find latest charge(include trashed) data for counting remaining of trial days.

Fix counting remaining trial days when recharge cancelled billing

---

src/ShopifyApp/Http/Middleware/AuthShopify.php

I was getting a PHP compile error on `implode` because I was sending other data through the an API route. Meaning I had payload data in my request and this function was not processing it correctly.
**Note:** I'm not entirely sure that `$shopify_values` actually contains all the values needed.

Only process needed request values

---

src/ShopifyApp/Actions/ActivatePlan.php

Fixes #444 
Checks if charge is RECURRING for activated_on attribute because this attribute only exists for RECURRING charge and causes error on ONETIME charge.

Adds isRecurring check for activated_on attribute in ActivatePlan

---

src/ShopifyApp/resources/database/migrations/2020_01_29_231006_create_charges_table.php

Laravel changed the user_id column to be a big increments in v5.8 and this bug was raised and fixed to cater for it:
https://github.com/osiset/laravel-shopify/issues/419
However, the version check excludes v5.8 when it should be included. This PR fixes the conditional version check.

correct version check for Laravel 5.8 introduction of bigIncrements

---

CONTRIBUTORS.txt
src/ShopifyApp/Http/Middleware/AuthProxy.php
src/ShopifyApp/helpers.php
tests/Http/Middleware/AuthProxyTest.php
tests/Http/Middleware/LegacyAuthProxy.php

Shopify does not parse the query string of a request with array parameters the same way as Laravel. While Laravel and most web frameworks parse `name[]=value` to `['name' => ['value']]`, Shopify parses it to `['name[]' => 'value']`. (When there are multiple parameters with the same name, Shopify will put the values in an array.)
The reason for this is shown in the [Shopify docs](https://shopify.dev/tutorials/display-data-on-an-online-store-with-an-application-proxy-app-extension): they use [`Rack::Util.parse_query`](https://github.com/rack/rack/blob/f9ad97fd69a6b3616d0a99e6bedcfb9de2f81f6c/lib/rack/query_parser.rb#L36).
```ruby
require 'rack/utils'
query_string = "extra=1&extra=2&shop=shop-name.myshopify.com&path_prefix=%2Fapps%2Fawesome_reviews&timestamp=1317327555&signature=a9718877bea71 …
```

Parse query strings the same as Shopify to support array parameters

---

src/ShopifyApp/Actions/ActivatePlan.php
src/ShopifyApp/Actions/GetPlanUrl.php
src/ShopifyApp/Contracts/ApiHelper.php
src/ShopifyApp/Objects/Enums/ApiMethod.php
src/ShopifyApp/Objects/Enums/ChargeInterval.php
src/ShopifyApp/Objects/Enums/ChargeType.php
src/ShopifyApp/Objects/Enums/PlanInterval.php
src/ShopifyApp/Objects/Transfers/PlanDetails.php
src/ShopifyApp/Services/ApiHelper.php
src/ShopifyApp/Services/ChargeHelper.php
src/ShopifyApp/Storage/Commands/Charge.php
src/ShopifyApp/Storage/Models/Plan.php
src/ShopifyApp/resources/database/factories/PlanFactory.php
src/ShopifyApp/resources/database/migrations/2020_07_03_211514_add_interval_column_to_charges_table.php
src/ShopifyApp/resources/database/migrations/2020_07_03_211854_add_interval_column_to_plans_table.php

Shopify adds an annual subscription to the Billing API in API ver 2020-07, this can only be done with GraphQL API. I added a migration file to add new columns `interval` to the `plans` and `charges` table to flag monthly or annual recurring.
`interval` column accept two values: **EVERY_30_DAYS** or **ANNUAL**. If the interval column is `NULL`, then the interval defaults to **EVERY_30_DAYS**.
Reference:
- [Shopify blog about Release API 2020-07](https://www.shopify.com/partners/blog/shopify-api-release-july-2020#annual-charges)
- [Shopify tutorial to create an annual subscription](https://shopify.dev/tutorials/create-an-annual-subscription)

Recurring annual subscription on Shopify API 2020-07

---

src/ShopifyApp/resources/routes.php

Fix the auth middleware name in route comment. The old name for the authentication middleware was `auth.shop` but the new middleware is `auth.shopify`
Note there is no functional changes here, this is solely updating a comment.

Fix old name for authentication middleware

---

src/ShopifyApp/Traits/ShopModel.php

This PR simply renames the boot method of the trait `ShopModel` so that this method is not accidentally overriden by a boot method set on the User model. This is done by use of Eloquents automatic boot naming conventions for traits - please see [this guide](https://tighten.co/blog/laravel-tip-bootable-model-traits/] by Tighten Co for more information.
A `User` model using the `ShopModel` trait might also implement its own `protected static function boot()` which causes the same method on the `ShopModel` trait to be overriden, causing the global scope to **not be** registred.
A `User` model using the `ShopModel` trait might also implement its own `protected static function boot()` which does not conflict with the `ShopModel` trait since Eloquent will automatically call the method …

Update ShopModel trait boot method

---

tests/Actions/ActivatePlanTest.php
tests/Actions/ActivateUsageChargeTest.php
tests/Actions/AfterAuthorizeTest.php
tests/Actions/AuthenticateShopTest.php
tests/Actions/AuthorizeShopTest.php
tests/Actions/CancelChargeTest.php
tests/Actions/CancelCurrentPlanTest.php
tests/Actions/CreateScriptsTest.php
tests/Actions/CreateWebhooksTest.php
tests/Actions/DeleteWebhooksTest.php
tests/Actions/DispatchScriptsTest.php
tests/Actions/DispatchWebhooksTest.php
tests/Actions/GetPlanUrlTest.php
tests/Http/Middleware/AuthShopifyTest.php
tests/Http/Middleware/BillableTest.php
tests/Services/ApiHelperTest.php
tests/Services/ChargeHelperTest.php
tests/Services/CookieHelperTest.php
tests/Services/ShopSessionTest.php
tests/Storage/Commands/ChargeTest.php
tests/Storage/Commands/ShopTest.php
tests/Storage/Queries/ChargeTest.php
tests/Storage/Queries/PlanTest.php
tests/Storage/Queries/ShopTest.php
tests/Traits/AuthControllerTest.php
tests/Traits/BillingControllerTest.php
tests/Traits/HomeControllerTest.php

Declare missing tests classes properties, and also add their docblocks if they are missing.

Declare missing tests classes properties

---

src/ShopifyApp/Console/stubs/webhook-job.stub

`$shopDomain` is not a string but an instance of `Osiset\ShopifyApp\Contracts\Objects\Values\ShopDomain`

Fix shopDomain type in php inline doc

---

composer.json

Based on information from https://github.com/orchestral/testbench/blob/6.x/README.md#using-legacy-factories
Unit tests for Laravel 8.1 are passing locally.

Updated composer.json to support legacy factories for Orchestra

---

src/ShopifyApp/helpers.php
src/ShopifyApp/resources/config/shopify-app.php
src/ShopifyApp/resources/routes.php
tests/HelpersTest.php

Relates to #596, needs physical testing.
Allows for someone to list out routes they wish to be excluded from registering with Laravel.
Example: `SHOPIFY_MANUAL_ROUTES=home,billing` would tell this package to not register the internal `home` and `billing` routes.

Ability to override internal routes #596

---

src/ShopifyApp/Http/Middleware/AuthShopify.php
src/ShopifyApp/Http/Middleware/Billable.php
src/ShopifyApp/Services/ConfigHelper.php
src/ShopifyApp/Traits/AuthController.php
src/ShopifyApp/Traits/BillingController.php
src/ShopifyApp/Traits/ConfigAccessible.php
src/ShopifyApp/resources/config/shopify-app.php
src/ShopifyApp/resources/routes/api.php
src/ShopifyApp/resources/routes/shopify.php
tests/HelpersTest.php

This implements the changes we discussed in #595. All route names can be configured through either the config file or through environment variables.
You mentioned `ConfigAccessible`, which is a huge help. However, given that it's a trait and only accessible in a class scope, I created a simple `ConfigHelper` wrapper class that has static `get()`, `set()`, and `setArray()` methods. This lets you use `ConfigAccessible` everywhere, regardless of scope. I used it in `resources/routes/shopify.php` and `resources/routes/api.php` to get `manual_routes` and `prefix`, as well as all of the route names.
An additional reason for creating `ConfigHelper` was because I had to add some additional logic to `ConfigAccessible->get()` to support dot-notation in the keys for the route names in the config …

Make route names configurable

---

src/ShopifyApp/Services/ApiHelper.php
src/ShopifyApp/resources/config/shopify-app.php

Reasoning behind this is to allow for using "Custom Apps" with the same code base. One could add a migration to the users table to store the custom app api key/secret for each shop, then in the config, utilize api_init option to pull the keys from the database for the shop.
This has been requested many times since Shopify now limits how apps work, you can not have an unpublished app installed on many stores. This "solution" will allow for same code base, and switching the API keys on the fly when the API interface is requested for the shop.

Pass session into api_init function

---

src/ShopifyApp/helpers.php
src/ShopifyApp/resources/routes/api.php
tests/HelpersTest.php

There was a bug in the code that made it impossible to exclude "api" routes using configuration. In addition, the Router class got into the function, I modified the function so that it could not happen in the future.

Hotfix exclude api register routes

---

src/ShopifyApp/Actions/DispatchScripts.php
src/ShopifyApp/Actions/DispatchWebhooks.php
src/ShopifyApp/Messaging/Jobs/ScripttagInstaller.php
src/ShopifyApp/Messaging/Jobs/WebhookInstaller.php
src/ShopifyApp/ShopifyAppProvider.php

Issue seems to not be present until latest version of Laravel. Job action class passed into dispatch scripts and dispatch webhooks jobs fails because it tries to serialize the class.
Modified flow to use `handle` to resolve the class needed.

Fix to remove job class from arguments passed to job

---

src/ShopifyApp/Traits/WebhookController.php

Currenly webhooks always dispatch into `default` queue, so WEBHOOKS_JOB_QUEUE setting in config not applied in WebhookController.

Fix webhooks dispatch into specified queue

---

src/ShopifyApp/Console/stubs/webhook-job.stub

Currently webhook stub use interface:
`use Osiset\ShopifyApp\Contracts\Objects\Values\ShopDomain;`
So this code produce error:
`public function handle()
{
// Convert domain
$this->shopDomain = ShopDomain::fromNative($this->domain);
// Do what you wish with the data
// Access domain name as $this->shopDomain->toNative()
}`
Right one use statement `use Osiset\ShopifyApp\Objects\Values\ShopDomain;`

Fix make webhook stub

---

src/ShopifyApp/Storage/Queries/Shop.php

Fix high usage of memory during installation occurs when users table has a lot of users.

Fix high usage of memory during installation

---

src/ShopifyApp/Services/ApiHelper.php
src/ShopifyApp/resources/views/layouts/default.blade.php

when using config_api_callback in configuration sometimes $shop is just null if i click on an internal url of my app, but the information is present in the referrer

Added read shop from referrer if everything fails

---

composer.json
src/ShopifyApp/Actions/AuthenticateShop.php
src/ShopifyApp/Exceptions/MissingAuthUrlException.php
src/ShopifyApp/Http/Middleware/Billable.php
src/ShopifyApp/Http/Middleware/VerifyShopify.php
src/ShopifyApp/Traits/AuthController.php
src/ShopifyApp/Traits/BillingController.php
src/ShopifyApp/helpers.php
src/ShopifyApp/resources/config/shopify-app.php
src/ShopifyApp/resources/routes/shopify.php
src/ShopifyApp/resources/views/layouts/default.blade.php

I added support for billing.
Also, when using Turbolinks (or Hotwire) token does not come through "$request->ajax() ", so I added appropriate setting in config, and accordingly slightly changed getting token from request.

Feature/cookieless - Billing, Turbo

---

src/ShopifyApp/helpers.php
src/ShopifyApp/resources/views/auth/token.blade.php

It was checking for "&" in the URLs when deciding whether to add "&" or "?", but it should check for "?" instead.
For example: `foo.bar/baz?blah` doesn't contain a "&" so it would append a "?" and return `foo.bar/baz?blah?token=...`

Check for "?" in URLs instead of "&" when determining the separator

---

src/ShopifyApp/Http/Middleware/VerifyShopify.php

When using a route prefix, `Str::startsWith($request->getRequestUri(), ['/authenticate', '/billing'])` isn't going to match the route URL. I changed it to `Str::contains()` so that it can be anywhere in the URL.
Case in point - my routes:
This can still potentially cause problems if the "authenticate" or "billing" routes are manually registered and _don't_ contain `/authenticate` or `/billing`. However, IMO that's a pretty big edge case that I don't think needs to be accounted for at this point.

Use `contains()` to support route prefixes

---

src/ShopifyApp/resources/config/shopify-app.php

Just a small change to bring it inline with the rest of the config file 👍🏻

Use an env var for the new `turbo_enabled` config setting

---

src/ShopifyApp/Traits/AuthController.php

If the `target` URL already has a `token` query param then it ends up doubling up in the subsequent request:
This PR removes "token" from the query params before passing it to the view

Remove "token" from the query string of the target URL

---

src/ShopifyApp/Http/Middleware/VerifyShopify.php
src/ShopifyApp/Traits/AuthController.php
src/ShopifyApp/resources/views/layouts/default.blade.php

In my case, when I tried to install the application, I was immediately redirected to /authenticate/token, which ended in an error. That's why I added a store check.
I also changed a little receiving and updating the token before sending Turbolinks request.
I also removed const from variables, because Turbo conflicts with constant variables.
Maybe it would be more correct to put them on a separate template

Feature/cookieless - changes for turbolinks, install app 

---

src/ShopifyApp/Http/Middleware/VerifyShopify.php
src/ShopifyApp/Objects/Values/SessionToken.php
src/ShopifyApp/Objects/Values/ShopDomain.php
src/ShopifyApp/Traits/AuthController.php

When redirecting within your app, it's easy to get into a state where there isn't a "shop" query param for the token controller to use. At that point you're completely stuck because you can't auth anymore. You're at the end of the road.
This PR adds a static method `ShopDomain::getFromRequest()` that tries to find the token in the request in multiple ways:
1. If the request inputs contain "shop" or "shopDomain", it is used.
2. If the request headers contain "X-Shop-Domain", it is used.
3. If the request headers have a referrer URL then the same checks are performed against it ("shop" and "shopDomain")
4. If the referrer URL contains a "token" query param, it is decoded and checked for a shop domain.
- To accomplish this, I added an optional param to the `SessionToken` constructor that …

Find shop domain in request when getting the token

---

src/ShopifyApp/Http/Middleware/VerifyShopify.php

I noticed that my routes that had query params were losing the query params when they were going through the token redirect route. The only way the query params were being passed through is if they included "hmac". This PR makes it so that query params (filtered) are always passed through to the token redirect route.
One thing to note is that I changed `$request->all()` to `$request->query()`. I couldn't think of any reason to use `all()` because that includes POST params, file keys, etc. Converting everything to query params could potentially cause some problems.

Always pass the filtered query params to the token redirect

---

src/ShopifyApp/Http/Middleware/VerifyShopify.php

Hoping I haven't done unintended here. I'm sure someone will tell me if I have. 
Removed host parameter from filter. AppBridge 2 requires this parameter to be set in initialisation, so having it on the url is very useful.
I bumped to 2.0.3 for this: 
`package.json`
"dependencies": {
"@shopify/app-bridge": "^2.0.3",
"@shopify/app-bridge-react": "^2.0.3",
"@shopify/app-bridge-utils": "^2.0.3"
...
As the host parameter is now available on the url, it could be placed on the blade template for my SPA
<input type="hidden" id="host" value="{{ \Request::get('host') }}" />
And included by my top js.
...
const config = {
host: document.getElementById("host").value,
...
}

Retain host parameter

---

src/ShopifyApp/resources/views/partials/token_handler.blade.php

Correct Authorization Bearer setting for jQuery ajax header

Update jQuery ajax header Authorization setting

---

.github/workflows/ci.yml

This PR fixes CI flags:
- remove deprecated `--no-suggest` flag
- add a verbose level for `phpunit`

Fix CI flags

---

tests/Traits/HomeControllerTest.php

Do not use `env()` helper outside the config file.

Do not use env() helper outside the config file.

---

src/ShopifyApp/Console/WebhookJobMakeCommand.php
src/ShopifyApp/Services/ApiHelper.php
src/ShopifyApp/Util.php
src/ShopifyApp/resources/config/shopify-app.php
tests/UtilTest.php

v17 requires webhooks to be configured with GraphQL-style webhook topics (e.g. "ORDERS_CREATE") instead of the previously-used REST-style webhook topics (e.g. "orders/create"). If there are webhooks in the config and `topic` isn't changed on all of them during the upgrade process, an exception is thrown that it isn't terribly clear how to fix: `Variable $topic of type WebhookSubscriptionTopic! was provided invalid value`.
This PR adds backward compatibility with REST-style webhook topics through the use of a new utility method: `Util::getGraphQLWebhookTopic(string $topic): string`
```php
Util::getGraphQLWebhookTopic('orders/created') === 'ORDERS_CREATED'
```
When the webhooks in the config are being created on the store, the `topic` is run through this method to ensure that the …

Add backward compatibility with REST-style webhook topics (e.g. "orders/create")

---

src/ShopifyApp/resources/config/shopify-app.php
tests/Services/ApiHelperTest.php

If you don't specify a Shopify API version in `.env` then it defaults to `2020-01`, which hasn't been supported since January 1, 2021. I increased the default to `2021-01`, which is supported until January 1, 2022 (~5 months). I also added a link to Shopify's versioning docs.

Increase default Shopify API version from `2020-01` to `2021-01`

---

src/ShopifyApp/Traits/AuthController.php

Sometimes when turbolinks were turned on the application did not install correctly

Turbulinks fixes

---

.gitattributes
.github/workflows/ci.yml
README.md
codecov.yml

Uses codecov instead of coversall

Uses codecov.

---

src/Traits/AuthController.php
src/resources/views/layouts/default.blade.php

AppBridge 2.0 (now required for successful submission) requires the host parameter, after redirect it is not available on the URL any longer. Include it here to make it easily available.
I'm not using the supplied views, mine are custom, and I need the host parameter to be more readily available when I instantiate appbridge.  This works fine.

:bug: Retain host parameter after successful install

---

ide.json

The popular [Laravel Idea PhpStorm plugin](https://laravel-idea.com/) allows custom configuration for the autocompletions through the use of a [config file `ide.json`](https://laravel-idea.com/docs/ide_json). This PR adds that file so that the token route macros will autocomplete the route names:

Add route autocompletion support for the Laravel Idea plugin

---

README.md

Linked page doesn't exist, no wiki page exists for "Requirements"

Removed Dead link in Readme, i.e. "Requirements"

---

src/Objects/Values/SessionToken.php

Fixes an issue where the verifyValidity() function checks the api token against the global api_key instead of any shop specific token.
Also fixes an infinite loop error that was occurring for myself, possibly related to: https://github.com/osiset/laravel-shopify/issues/962

Bugfix incorrect api_key in SessionToken function

---

.github/workflows/ci.yml
src/resources/config/shopify-app.php
tests/Services/ApiHelperTest.php

This updates the default API version to be `2022-01` because `2021-01` is no longer supported.
It will flag up deprecation an error for apps like so:

Update the API version to 2022-01

---

composer.json

`ergebnis/composer-normalize` is being stopped by composer to normalize because it is not an allowed plugin and this is killing the tests in the workflows.

Allow ergebnis/composer-normalize to run the code clean on workflows

---

src/Traits/BillingController.php

Fix PHP 8.0: Deprecate required parameters after optional parameters in function/method signatures

Propose to fix Billable app throwing exception on install

---

src/Http/Middleware/IframeProtection.php
src/ShopifyAppProvider.php
tests/Http/Middleware/IframeProtectionTest.php

At the moment, if you do not set some of the headers, the application will not pass the review.
This header (frame-ancestors) allows you to open the application in an iframe only from an allowed domain

Setting up Iframe protection

---

src/resources/config/shopify-app.php
src/resources/views/partials/token_handler.blade.php

This PR adds the refresh token interval found in `token.blade` to the config so that the default time of 2 seconds can be changed by the user.
This helps #1116 and #1076

Feature | Add Session Refresh Time to ENV

---

src/Http/Middleware/VerifyShopify.php
src/Objects/Values/ShopDomain.php
src/Services/ApiHelper.php
tests/TestCase.php

* Fixes deprecation notices for PHP8
* Adds deprecation logging support to tests being run
Mainly, `parse_url` and `parse_str` calls have been updated. Warnings were present complaining about possible null values where a string is expected.
This PR adjusts to check for falsey/null and use a empty string as fallback.

Deprecation supports and fixes

---

src/Console/AddVariablesCommand.php
src/ShopifyAppProvider.php
tests/Console/AddVariablesCommandTest.php

You will probably add variables to the .env one way or another.
This command just simplifies the this process

Add variables command

---

src/resources/views/auth/fullpage_redirect.blade.php
tests/TestCase.php

Currently the authenticated route can break usually on a proper visit to /authenticate because of the `{{!! !!}}` formatting in the blade template for the api key, shop origin and host.

Removed `!!` from the full_page_redirect breaking authenticate route

---

src/Http/Requests/StoreUsageCharge.php
src/Traits/BillingController.php
tests/Traits/BillingControllerTest.php

Currently, the usage Charge method is trying to get the user from the session but it is not available.
This updates the route to expect the shop domain to be passed in like the other functions.

Usage Charge "ID on Null" Fix

---

src/resources/views/partials/token_handler.blade.php

Currently there is no support for Livewire 2.x. This PR provides support for Livewire 2.x by incorporating the required headers into `token_handler.blade.php`.
This closes #1245

Updates to token_handler.blade.php to support Livewire 2.x

---

.github/workflows/ci.yml
src/Traits/BillingController.php
tests/Traits/BillingControllerTest.php

Currently when trying to use AppBridge within an SPA, if we leave the SPA context like when billing happens we need to not only pass the shop param but also the new host param that shopify uses to load AppBridge.

AppBridge : Add the host param to the billing redirect url
